#!/usr/bin/env bash
# =============================================================================
# attribution-guard.sh — AI tools are never credited. Refuses AI tool names
# (including in Co-authored-by lines), Assisted-by trailers, and "generated"
# footers in tracked files and commit messages. Co-authored-by lines for
# people and for GitHub's dependency bot are allowed.
#
#   attribution-guard.sh tree            scan every tracked file
#   attribution-guard.sh msg <file>      scan one commit message (commit-msg hook)
#   attribution-guard.sh range <a>..<b>  scan every commit message in a range
#   attribution-guard.sh selftest        verify the pattern against known cases
# =============================================================================
set -euo pipefail
ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
SELF="scripts/attribution-guard.sh"

PATTERN='(^|[^[:alnum:]])(claude|anthropic|openai|chatgpt|copilot|codex|gemini)([^[:alnum:]]|$)|assisted-by:|generated (with|by) \[?(an? )?(ai|llm|tool)'

fail() { echo "FAIL: $1"; exit 1; }

case "${1:-}" in
    tree)
        if git -C "$ROOT" ls-files -z | grep -zv "^$SELF\$" \
            | (cd "$ROOT" && xargs -0 grep -nIiE "$PATTERN" --); then
            fail "tool attribution or tool reference in tracked files"
        fi
        # File and directory names count too.
        if git -C "$ROOT" ls-files | grep -v "^$SELF\$" | grep -iE "$PATTERN"; then
            fail "tool reference in a tracked path"
        fi
        ;;
    msg)
        [[ -f "${2:-}" ]] || fail "usage: $0 msg <file>"
        if grep -v '^#' "$2" | grep -niE "$PATTERN"; then
            fail "tool attribution in commit message"
        fi
        ;;
    range)
        [[ -n "${2:-}" ]] || fail "usage: $0 range <a>..<b>"
        if git -C "$ROOT" log --format='%H%n%an <%ae>%n%cn <%ce>%n%B' "$2" | grep -niE "$PATTERN"; then
            fail "tool attribution in commit messages or identities of $2"
        fi
        ;;
    selftest)
        must_fail=(
            "Assisted-by: any tool"
            "Co-Authored-By: Claude <noreply@anthropic.com>"
            "Co-authored-by: GitHub Copilot <copilot@github.com>"
            "Generated with [Claude Code](https://claude.com)"
            "generated by AI"
            "tweaked with codex"
        )
        must_pass=(
            "Co-authored-by: Jake Abendroth <jake@example.com>"
            "Co-authored-by: dependabot[bot] <49699333+dependabot[bot]@users.noreply.github.com>"
            "feat: add HPKE framing"
            "build: bump the cargo lockfile (generated by cargo)"
        )
        for line in "${must_fail[@]}"; do
            grep -qiE "$PATTERN" <<<"$line" || fail "selftest: not refused: $line"
        done
        for line in "${must_pass[@]}"; do
            ! grep -qiE "$PATTERN" <<<"$line" || fail "selftest: wrongly refused: $line"
        done
        echo "attribution guard selftest passed"
        ;;
    *)
        fail "usage: $0 tree | msg <file> | range <a>..<b> | selftest"
        ;;
esac
